### ISSUE TITLE
Create a complete backup of old site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-idintegration#2]
Remember how I had you review the process for creating a carbon copy of a client's site? 

Now I need you to do it for a current client of ours: http://www.id-integration.com/

There should already be a folder created for this project in our google drive. Remember, try to follow the procedure the previous intern did.

due:
1-6-16  4p

**Comment by rampage1213** [comment]
This is done! I did this a little different from past projects. What I did was installed httrack and downloaded the complete site, this lets anyone run the backed up site local. There is also a folder with the main screenshots for the site.

**Comment by rampage1213** [comment]
@rodneystrong Please let me know if there is anything I missed on this.

**Comment by rodneystrong** [comment]
Excellent work sir. I'll need to load this locally on my desktop at home to test it out due to space limitations on mac.

**Comment by rodneystrong** [comment]
Good job dude, we got it all
