### ISSUE TITLE
Upload new versions of slider images (DUE 1PM TODAY!!)

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-idintegration#5]
Shel and Chris,

 I know we just talked, but this is just a follow-up.

 Just got done talking and checked the Box.com link you gave (https://app.box.com/s/7mz9nhzt207wyxqqe5t2uivfkf6k3flm)  

 Unfortunately there's only one high res image in the box.com link  (aircraft carrier). Currently we're using ones from the live site (idintegration.com). If you could upload high res versions of all the other photos (jet, helicopter, tank, rocket launch) we'll get them cropped and up on the test site. 

Cheers,
Alex

Joel, once I get an email from Chris, I'll forward it to you to do. In the mean time, stay tuned.

due:
1-11-16   1pm

**Comment by jperez4509** [comment]
This has been completed.
