### ISSUE TITLE
Create Sitemap

### ISSUE THREAD

**Issue by jperez4509** [EditLLC/client-idintegration#6]
@rampage1213 Can you assist me with creating a sitemap of the entire site for ID Integration. I need to know how the site is structured for all of the menu nav links and the side bar nav links. Please create a bullet point list with sub-bullets for child pages and so on. I think it would help if you put the name of the page and the link.

**Comment by rampage1213** [comment]
I have laid out to my best ability a full sitemap of their site. Their site gets a little complex and is a maze. I made a new folder in the google drive and made a google doc titled site map here is the link. https://drive.google.com/drive/folders/0BwAKenYDnaLfT3kxRFlldzUzNTA
